
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for axi2apb_bridge.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.0.2.beta1
//* Generated on: Dec. 23, 2010 02:21:14 PM, (user: sagihb)
//* Automatically merged on: Feb. 04, 2011 10:36:59 AM, (user: zamir)
//* Automatically merged on: Sep. 07, 2011 11:39:44 AM, (user: awinterg)
//* Automatically merged on: Feb. 22, 2012 07:00:49 PM, (user: zamir)
//* Automatically merged on: Aug. 26, 2013 11:45:53 AM, (user: ahanga)
//* Automatically merged on: Oct. 11, 2013 04:28:21 PM, (user: johns)
//* Automatically merged on: Jan. 09, 2014 07:31:17 PM, (user: johns)
//* Automatically merged on: Jan. 18, 2016 04:09:45 PM, (user: mbradley)
//*>


#include "axi2apb_bridge_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
axi2apb_bridge_pv::axi2apb_bridge_pv(sc_module_name module_name) 
  : axi2apb_bridge_pv_base(module_name) {
}      

// Read callback for axi_slave port.
// Returns true when successful.
bool axi2apb_bridge_pv::axi_slave_callback_read(mb_address_type address, unsigned char* data, unsigned size) {
  
  return apb_master_read(address, data, size);
}


// Write callback for axi_slave port.
// Returns true when successful.
bool axi2apb_bridge_pv::axi_slave_callback_write(mb_address_type address, unsigned char* data, unsigned size) {
  
  return apb_master_write(address, data, size);
}


unsigned axi2apb_bridge_pv::axi_slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
}

unsigned axi2apb_bridge_pv::axi_slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
}

bool axi2apb_bridge_pv::axi_slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

 
