
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for axi2apb_bridge.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 3.0.2.beta1
//* Generated on: Dec. 23, 2010 02:21:14 PM, (user: sagihb)
//* Automatically merged on: Feb. 04, 2011 10:36:59 AM, (user: zamir)
//* Automatically merged on: Feb. 27, 2011 07:18:09 PM, (user: zamir)
//* Automatically merged on: Sep. 07, 2011 11:39:44 AM, (user: awinterg)
//* Automatically merged on: Oct. 28, 2011 02:11:17 PM, (user: zamir)
//* Automatically merged on: Feb. 22, 2012 07:00:49 PM, (user: zamir)
//* Automatically merged on: Aug. 16, 2012 12:58:15 PM, (user: araskin)
//* Automatically merged on: Dec. 03, 2012 05:56:37 PM, (user: mbradley)
//* Automatically merged on: Aug. 26, 2013 11:45:53 AM, (user: ahanga)
//* Automatically merged on: Oct. 11, 2013 04:28:21 PM, (user: johns)
//* Automatically merged on: Jan. 09, 2014 07:31:17 PM, (user: johns)
//* Automatically merged on: Jan. 18, 2016 04:09:45 PM, (user: mbradley)
//*>


#pragma once

#include "axi2apb_bridge_model.h"

using namespace tlm;

//This class inherits from the axi2apb_bridge_pv_base class
class axi2apb_bridge_pv : public axi2apb_bridge_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(axi2apb_bridge_pv);
  axi2apb_bridge_pv(sc_core::sc_module_name module_name);    

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool axi_slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned axi_slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool axi_slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned axi_slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);  
  bool axi_slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

