
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for IO.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 3.1.0
//* Generated on: Mar. 02, 2011 05:47:43 PM, (user: dvolinsk)
//* Automatically merged on: Sep. 07, 2011 11:39:33 AM, (user: awinterg)
//* Automatically merged on: Feb. 22, 2012 07:00:34 PM, (user: zamir)
//* Automatically merged on: Apr. 16, 2014 02:34:43 AM, (user: awinterg)
//*>


#include "IO_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

IO_t_base* IO_t_base::create_t(const char* name, long simulation) {
  return new IO_t(name, simulation);
}

IO_t::IO_t(sc_module_name _name, long simulation)
  : IO_t_base(_name, simulation) {
  
}

