
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for smc91x.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 3.8.0RC1
//* Generated on: Apr. 16, 2014 02:34:40 AM, (user: awinterg)
//*>


#include "smc91x_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

smc91x_t_base* smc91x_t_base::create_t(const char* name, long simulation) {
  return new smc91x_t(name, simulation);
}

smc91x_t::smc91x_t(sc_module_name _name, long simulation)
  : smc91x_t_base(_name, simulation) {
  
}

