
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for sram.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 3.0.2.beta1
//* Generated on: Dec. 23, 2010 01:59:33 PM, (user: sagihb)
//* Automatically merged on: Feb. 04, 2011 10:37:07 AM, (user: zamir)
//* Automatically merged on: Sep. 07, 2011 11:39:51 AM, (user: awinterg)
//* Automatically merged on: Feb. 22, 2012 07:01:00 PM, (user: zamir)
//* Automatically merged on: Apr. 16, 2014 02:34:45 AM, (user: awinterg)
//*>


#include "sram_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

sram_t_base* sram_t_base::create_t(const char* name, long simulation) {
  return new sram_t(name, simulation);
}

sram_t::sram_t(sc_module_name _name, long simulation)
  : sram_t_base(_name, simulation) {
  
}

