
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2012     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for UART_Visualization_Linux.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 3.4.0
//* Generated on: Sep. 10, 2012 08:56:46 PM, (user: mbradley)
//* Automatically merged on: Apr. 16, 2014 02:34:41 AM, (user: awinterg)
//*>


#include "UART_Visualization_Linux_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

UART_Visualization_Linux_t_base* UART_Visualization_Linux_t_base::create_t(const char* name, long simulation) {
  return new UART_Visualization_Linux_t(name, simulation);
}

UART_Visualization_Linux_t::UART_Visualization_Linux_t(sc_module_name _name, long simulation)
  : UART_Visualization_Linux_t_base(_name, simulation) {
  
}

