#!/bin/sh

mkdir -p $SYSROOT/etc
mkdir -p $SYSROOT/etc/init.d
mkdir -p $SYSROOT/etc/network/if-down.d
mkdir -p $SYSROOT/etc/network/if-post-down.d
mkdir -p $SYSROOT/etc/network/if-pre-up.d
mkdir -p $SYSROOT/etc/network/if-up.d
mkdir -p $SYSROOT/root
mkdir -p $SYSROOT/var/run
mkdir -p $SYSROOT/var/log
touch $SYSROOT/var/log/lastlog


cat > $SYSROOT/etc/group <<EOF
root:x:0:
EOF

cat > $SYSROOT/etc/inittab <<EOF
::sysinit:/etc/init.d/rcS
::respawn:/sbin/getty -L 115200 ttyAMA0 vt102
EOF

cat > $SYSROOT/etc/network/interfaces <<EOF
auto lo
iface lo inet loopback
EOF

cat > $SYSROOT/etc/passwd <<EOF
root:\$1\$BAE6PsyQ\$NpNXsYDmGKvrQrja/qrI11:0:0:root:/root:/bin/sh
EOF

cat > $SYSROOT/etc/resolv.conf <<EOF
nameserver 10.0.2.3
EOF

cat > $SYSROOT/etc/version <<EOF
Mentor Graphics Cortex A9 MP Linux Demo
EOF

cat > $SYSROOT/etc/init.d/rcS <<EOF
#!/bin/sh

# Mount /proc
echo Mounting /proc
mkdir -p /proc
mount -t proc proc /proc

# Mount /sys
echo Mounting /sys
mkdir -p /sys
mount -t sysfs sys /sys

# devices

echo Devices:
mkdir -p /dev

echo "   mem kmem null zero urandom"
mknod /dev/mem         c 1 1
mknod /dev/kmem        c 1 2
mknod /dev/null        c 1 3
mknod /dev/zero        c 1 5
mknod /dev/urandom     c 1 9

echo "   ttyAMA0 ttyAMA1"
mknod /dev/ttyAMA0     c 204 64
mknod /dev/ttyAMA1     c 204 65

echo "   tty0 tty1 tty console ptmx pts"
mknod /dev/tty0        c 4 0
mknod /dev/tty1        c 4 1
mknod /dev/tty         c 5 0
test -c /dev/console || mknod /dev/console     c 5 1
mknod /dev/ptmx        c 5 2
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

echo "   fb0"
mknod /dev/fb0         c 29 0

echo "Setting hostname to demo"
hostname demo

echo "Configuring network"
ifconfig lo 127.0.0.1 up
ifconfig eth0 10.0.2.15 up
ip route add default via 10.0.2.2

echo "Sync date from host timeserver"
rdate 10.0.2.2
EOF

chmod +x $SYSROOT/etc/init.d/rcS
